### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by selatamil** [philsch/ansible-redshift#16]
I have given only localhost in the inventory and ran the playbook, it's searching for the pg_hba.conf entry in the localhost and failing to connect to the redshift database.

**Comment by selatamil** [comment]
@philsch additional info Test Redshift connection (check all.yml if this fails!) is changing to localhost

**Comment by philsch** [comment]
Hi @selatamil 

Do I understand correctly that you are trying to run the integration tests on your local computer? Here are some thing you can try:

- ensure you have installed the psql client (is `which psql` returning something?)
- ensure your python environment is working and you have installed the pg8000 package (is `pip list | grep pg8000` returning the package?)
- have you created the file `all.yml` and set up the correct url to your running Redshift instance?
- you can try to add `--connection=local` when running the tests: `export ANSIBLE_LIBRARY=../../lib/ && ansible-playbook 000_test_all.yml --connection=local  -i "127.0.0.1,"`

If this is not working, please provide some additional information. Also running ansible with `-vvv` verbose mode and pasting the log here can help to identify the problem.

**Comment by selatamil** [comment]
@philsch Thank you for your quick reply! Sure will try it out and let you know the verbose output if i didn't work. 

Error before trying:

$ ansible-playbook create_user.yml

 

PLAY [Test Create User] *******************************************************************************************************************

 

TASK [Gathering Facts] ********************************************************************************************************************

ok: [localhost]


TASK [prepare : Ensure psql client installed (check all.yml and installed packages if this fails!)] ***************************************

changed: [localhost]

TASK [prepare : Test Redshift connection (check all.yml if this fails!)] ******************************************************************

changed: [localhost]

 

TASK [prepare : Ensure no test user is present] *******************************************************************************************

changed: [localhost] => (item=test_user1)

 
TASK [prepare : Ensure no test group is present] ******************************************************************************************

changed: [localhost] => (item=test_grp_group1)

 

TASK [create_user : Create Testuser] ******************************************************************************************************

fatal: [localhost]: FAILED! => {"changed": false, "msg": "unable to connect to database: (u'FATAL', u'28000', u'no pg_hba.conf entry for host \"::ffff:x.x.x.x\", user \"dapdbadmin\", database \"bidevdb\", SSL off', u'/home/ec2-user/padb/src/pg/src/backend/libpq/auth.c', u'466', u'ClientAuthentication')"}

**Comment by philsch** [comment]
* Have you created create_user.yml? Because the only runbook in this repository with a similar name would be `100_test_create_user.yml`.
* Please double check if your ansible run is using the correct Redshift connection settins. You can do this by appending `-vvv` to your command... in the verbose output check the value `login_host` etc. if it matches your AWS Redshift database
```
TASK [test_create_user : Create Testuser] ********************
...
changed: [X.X.X.X] => {
    "changed": true,
    "group": "",
    "group_added": false,
    "group_removed": false,
    "invocation": {
        "module_args": {
            "conn_limit": "10",
            "db": "tracking",
            "expires": null,
            "group": "",
            "login_host": "*****HERE_YOUR_REDSHIFT_HOST_SHOULD_APPEAR*****",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_unix_socket": "",
            "login_user": "*****HERE_YOUR_REDSHIFT_USER_SHOULD_APPEAR*****",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "permission_flags": [],
            "port": 5439,
            "privs": [],
            "state": "present",
            "update_password": "always",
            "user": "test_user1"
        }
    },
....
```

**Comment by selatamil** [comment]
@philsch Please find the required details

$pip list | grep pg8000
pg8000                  1.12.2

$ export ANSIBLE_LIBRARY=./library/

$ ansible-playbook -vvv create_user.yml --connection=local -i "127.0.0.1,"               ansible-playbook 2.6.2

  config file = /path/ansible.cfg

  configured module search path = [u'/path/library']

  ansible python module location = /usr/lib/python2.7/site-packages/ansible

  executable location = /usr/bin/ansible-playbook

  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

Using /path/ansible.cfg as config file

Parsed 127.0.0.1, inventory source with host_list plugin

statically imported: /path/roles/create_user/tasks/execute.yml

statically imported: /path/roles/create_user/tasks/validate.yml

 

PLAYBOOK: create_user.yml ***************************************************************************************************

1 plays in create_user.yml

[WARNING]: Could not match supplied host pattern, ignoring: ansible

PLAY [Test Create User] *****************************************************************************************************

skipping: no hosts matched

PLAY RECAP ******************************************************************************************************************

 

$ cat vim create_user.yml

---
- name: Test Create User
  hosts: ansible
  roles:
    - prepare
    - create_user


$ cat inventory.ini
[ansible]
localhost

**Comment by philsch** [comment]
@selatamil thanks for your reply, unfortunately as you can see no host was matched in your playbook and therefore the log does not provide much useful information.

I think you are mixing up the integration tests provided by this library and the usage of this library. You have to write your own runbook and roles as documented in the Ansible documentation. The roles which are currently used in your `create_user.yml` (prepare and create_user) are intended to be used by the integration tests only!

I would suggest you create a simple example with the following setup:

* create your own `roles` directory and create a task in it like described in the README
* consider to create an EC2 instance (t2.micro is sufficient) and define the public IP address as `host` in your playbook... Ansible is intended to be executed with a remote target, running it in localhost-mode can make troubleshooting harder.

At the moment I can not see that your bug is related to this module itself. Without a basic ansible project and your `-vvv` log showing the actual usage of this module I can not help you at the moment. 

Thank you for your understanding.

**Comment by nidhinnru** [comment]
@selatamil @philsch I had the same error and I found it is an issue with SSL being turned off. Enabling the SSL in library redshift_user.py fixed the issue.

db_connection = pg8000.connect(**kw)
to
db_connection = pg8000.connect(SSL=True, **kw)

**Comment by philsch** [comment]
@nidhinnru thanks for clarifying, I'll provide an updated version which sets the SSL flag by default and introduces a new module parameter to turn SSL off if needed.
